services:

  postgres:
    image: postgres
    container_name: postgres-provinces
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    volumes:
      - /home/atf/db/wealthofnation-postgres:/var/lib/postgresql/data
    networks:
      - backend

  proveditor:
    build: .
    container_name: proveditor
    ports:
      - "5077:8080"
    depends_on:
      - postgres
    networks:
      - backend

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
#      - "5077:5077"
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - backend
      - ops
    depends_on:
      - proveditor
    extra_hosts:
      - host.docker.internal:host-gateway

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=user
      - GF_SECURITY_ADMIN_PASSWORD=pass
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    networks:
      - ops
    depends_on:
      - prometheus


volumes:
  prom_data:

networks:
  ops:
  backend:
  frontend:

# we probably need to put Promtehus and Grafana tohether in one network !