using Google.Apis.Auth;

namespace ProvEditorNET.Interfaces;

// *******************************************************
// keep in mind difference between idToken and accessToken
// idToken is widely used and is by default generated by
// e.g.: VueJS's vue3-google-login and easily consumed by
// Google.Apis.Auth.GoogleJsonWebSignature method
// accessToken on the other hand is handled manually by
// calling: GET https://www.googleapis.com/oauth2/v3/userinfo Headers: { Authorization: Bearer ya29.a0AeDClZBQXdb3ZRaMCuqguVi1h-jUXXXX }
// both can be used for SSO Login
// *******************************************************

public interface IGoogleAuth
{
    Task<GoogleJsonWebSignature.Payload> AuthenticateIdToken(string token);
    Task<string> AuthorizeAccessToken(string token);
}